[package]
name = "rustInk"
version = "0.1.0"
resources = ["src/ui/icons"]
edition = "2024"

[dependencies]
gtk    = { version = "0.18", features = ["v3_24"] }
gdk    = { version = "0.18" }
glib   = "0.18"
gio    = "0.18"
cairo-rs   = { version = "0.18", features=["pdf"] }
rusqlite   = { version = "0.31", features = ["bundled"] }
zip        = { version = "2", default-features = false, features = ["deflate"] }
quick-xml  = "0.31.0"
flate2     = "1"
serde      = { version = "1", features = ["derive"] }
bincode    = "1"   
pango      = "0.18"
pangocairo = "0.18"
image = { version = "0.25", features = ["webp"] }
tempfile = "3"
fs2 = "0.4"
lazy_static = "1.4.0"
poppler-rs = { version = "0.22", features = ["v20_9"] }
uuid = { version = "1", features = ["v4"] }
lopdf = "0.33.0"
base64 = "0.22.1"
rayon = "1.10"

[package.metadata.deb]
maintainer = "Mattia Perna"
copyright = "2026, Mattia Perna"
extended-description = "Note taking application in Rust"
depends = "$auto, libgtk-3-0, libpoppler-glib8"
assets = [
    ["target/release/rustInk", "usr/bin/", "755"],
    ["src/ui/icons/*", "usr/bin/icons/", "644"]
]

[package.metadata.bundle]
name = "RustInk"
identifier = "com.mattia939.rustink"
resources = ["src/ui/icons"]
version = "1.0.0"