[package]
name = "rastin-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1.3", features = ["derive"] }
RASTIN = { path = ".." }

# Isola la cartella fuzz per evitare conflitti di workspace con il progetto principale
[workspace]
members = ["."]

# Dichiara il target di fuzzing
[[bin]]
name = "fuzz_target"
path = "fuzz_targets/fuzz_target.rs"
test = false
doc = false